#!/usr/bin/env python3

# Author: Muhammad Ali Qureshi
# CSC 574 Mini-Project 1
# eft: encrypted file transfer

# Import additional modules as needed.
import argparse
import sys
import socket
from Crypto.Protocol.KDF import PBKDF2
from Crypto.Cipher import AES
from Crypto.Random import get_random_bytes
from Crypto.Util.Padding import pad,unpad


def print_debug(*objects, sep=' ', end='\n', file=sys.stderr, flush=False):
    """
    When stdout is redirected, messages cannot be printed to stdout as they will be written to the file, not the console.
    Use this function to print debug messages to stderr.
    It supports all optional arguments of the print function, with the exception that file is overridden to stderr.

    :param objects: Any non-keyword argument that can be converted to string.
    :param sep: String to separate objects. [Default: Space]
    :param end: String to append to the end. [Default: Newline]
    :param file: Not used. Overridden to sys.stderr.
    :param flush: Forcibly flush the stream.
    """

    print(objects, sep=sep, end=end, file=sys.stderr, flush=flush)


def read_file(buffer_len):
    """
    Wrapper function for reading from stdin.
    Use < to redirect a file to stdin.

    :param buffer_len: Number of bytes to read at once.
    :return: Raw bytes or None if buffer is empty.
    """
    return sys.stdin.buffer.read(buffer_len)


def write_file(data):
    """
    Wrapper function for writing a file to stdout.
    Use > to redirect stdout to a file.

    :param data: raw bytes.
    """
    sys.stdout.buffer.write(data)


def server(port, plain_key):
    """
    Server Code

    :param port: Port number to listen on.
    :param plain_key: Plain text decryption key.
    """
    server = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    host = '127.0.0.1'
    server.bind((host,port))
    server.listen(1)

    client,addr = server.accept()
    salt = client.recv(16)

    key = PBKDF2(plain_key,salt,32)

    broken = False
    while True:
        header = client.recv(2)
        if header == b'':
            break
        datalength = int.from_bytes(header,'big')
        init_vector = client.recv(16)
        tag = client.recv(16)
        ciphertext = client.recv(datalength-32)
        cipher = AES.new(key, AES.MODE_GCM, init_vector)
        try:
            data = cipher.decrypt_and_verify(ciphertext, tag)
            sys.stdout.buffer.write(unpad(data,block_size=16,style='pkcs7'))
        except :
            sys.stderr.write('Error: integrity check failed.')
            broken = True
            break

    if not broken:
        print_debug('File Transferred') 

    client.close()
    server.close()

def client(addr, port, plain_key):
    """
    Client Code

    :param addr: IP address of the server.
    :param port: Port to connect to.
    :param plain_key: Plain text encryption key.
    :return:
    """
    cSocket = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    cSocket.connect((addr,port))
    
    salt = get_random_bytes(16)
    cSocket.send(salt)

    key = PBKDF2(plain_key,salt,32)
    
    data = sys.stdin.buffer.read()
    datalength = len(data)
    for i in range(0,datalength,1024):
        cipher = AES.new(key,AES.MODE_GCM)
        datablock = data[i:min(i+1024,datalength)]
        init_vector = cipher.nonce
        ciphertext, tag = cipher.encrypt_and_digest(pad(datablock,block_size=16,style='pkcs7'))
        blocklength = len(ciphertext) + 32
        datablock = blocklength.to_bytes(2,'big') + init_vector + tag + ciphertext
        cSocket.send(datablock)

    cSocket.shutdown(socket.SHUT_WR)
    cSocket.close()

def parse_args():
    """
    Command Line Argument Parser

    :return: Argparse Namespace of identified command line arguments.
    """
    # Configure the argument parser.
    parser = argparse.ArgumentParser(description='Encrypted File Transfer')
    parser.add_argument('-k', dest='key', action='store', help='Password for key')
    server_group = parser.add_argument_group('server_group', 'Server mode options')
    server_group.add_argument('-l', dest='server_port', action='store', help='Server mode with port')
    client_group = parser.add_argument_group('client_group', 'Client mode options')
    client_group.add_argument('client_ip_address', nargs='?')
    client_group.add_argument('client_port', nargs='?')

    # Parse arguments.
    args = parser.parse_args()

    # Check if arguments are valid.
    args_ok = ((args.key is not None) and (args.server_port is None) and (args.client_ip_address is not None and args.client_port is not None)) or \
              ((args.key is not None) and (args.server_port is not None) and (args.client_ip_address is None and args.client_port is None))

    # If not, show usage message and exit.
    if not args_ok:
        print("./eft -k KEY [-l SERVER_PORT] [CLIENT_IP_ADDRESS CLIENT_PORT]")
        sys.exit(0)

    # Otherwise return the args.
    return args


def main():
    # Parse Arguments
    args = parse_args()

    # Launch the client or server depending on the arguments received.
    plain_key = args.key
    if args.server_port is not None:
        port = int(args.server_port)
        server(port, plain_key)
    else:
        addr = args.client_ip_address
        port = int(args.client_port)
        client(addr, port, plain_key)


if __name__ == "__main__":
    main()
