#!/usr/bin/env python3

# Author: Muhammad Ali Qureshi
# CSC 574 Mini-Project 1
# eft-dh: encrypted file transfer using DH key exchange

# Import additional modules as needed.
import argparse
import sys
import socket
from Crypto.Protocol.KDF import PBKDF2
from Crypto.Cipher import AES
from Crypto.Random import get_random_bytes
from Crypto.Random import random
from Crypto.Hash import SHA256
from Crypto.Util.Padding import pad,unpad

# Diffie-Hellman Parameters
g=2
p=0x100000000


def print_debug(*objects, sep=' ', end='\n', file=sys.stderr, flush=False):
    """
    When stdout is redirected, messages cannot be printed to stdout as they will be written to the file, not the console.
    Use this function to print debug messages to stderr.
    It supports all optional arguments of the print function, with the exception that file is overridden to stderr.

    :param objects: Any non-keyword argument that can be converted to string.
    :param sep: String to separate objects. [Default: Space]
    :param end: String to append to the end. [Default: Newline]
    :param file: Not used. Overridden to sys.stderr.
    :param flush: Forcibly flush the stream.
    """

    print(objects, sep=sep, end=end, file=sys.stderr, flush=flush)


def read_file(buffer_len):
    """
    Wrapper function for reading from stdin.
    Use < to redirect a file to stdin.

    :param buffer_len: Number of bytes to read at once.
    :return: Raw bytes or None if buffer is empty.
    """
    return sys.stdin.buffer.read(buffer_len)


def write_file(data):
    """
    Wrapper function for writing a file to stdout.
    Use > to redirect stdout to a file.

    :param data: raw bytes.
    """
    sys.stdout.buffer.write(data)


def num_to_x_byte_str(num,numbytes):
    """
    Converts int to numbytes-byte string with a bunch of 0s in front of it
    IMPORTANT: This function should NOT be used when creating the string representation of the output of the
                diffie-hellman key agreement procedure before hashing it. Use create_final_dh_string instead.


    :param num: The number to be encoded.
    :param numbytes:  The total number of bytes the string should take.
    :return: decimal representation of num padded with zeros.
    """

    num = str(num)
    return (numbytes-len(num))*'0' + num


def create_final_dh_string(new_key):
    """
    Process the output of the diffie_hellman key into a hex string for use in generating the session key.
    IMPORTANT: This function should NOT be used when creating the string representation of A and B.
               Use num_to_x_byte_str instead.

    :param new_key: Diffie-Hellman Key
    :return: Hex string representation of new_key.
    """

    # Post-process the created key
    new_key_str = '%x' % new_key

    return new_key_str.encode('utf-8')


def server(port):
    """
    Server Code

    :param port: Port number to listen on.
    """

    server = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    host = '127.0.0.1'
    server.bind((host,port))
    server.listen(1)

    client,addr = server.accept()

    b = random.randint(1,p-1)
    B = pow(g,b,p)
    B = int(num_to_x_byte_str(B,384))

    A = int.from_bytes(client.recv(384),'big')
    client.send(B.to_bytes(384,'big'))

    password = pow(A,b,p)
    dh_string = create_final_dh_string(password)
    hash_dh_string = SHA256.new(dh_string)
    key = hash_dh_string.digest()[:32]
    
    broken = False
    while True:
        header = client.recv(2)
        if header == b'':
            break
        datalength = int.from_bytes(header,'big')
        init_vector = client.recv(16)
        tag = client.recv(16)
        ciphertext = client.recv(datalength-32)
        cipher = AES.new(key, AES.MODE_GCM, init_vector)
        try:
            data = cipher.decrypt_and_verify(ciphertext, tag)
            sys.stdout.buffer.write(unpad(data,block_size=16,style='pkcs7'))
        except :
            print_debug('Error: integrity check failed.')
            broken = True
            break

    if not broken:
        print_debug('File Transferred') 

    client.close()
    server.close()


def client(addr, port):
    """
    Client Code
    :param addr: IP address of the server.
    :param port: Port to connect to.
    :return:
    """
    cSocket = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    cSocket.connect((addr,port))

    a = random.randint(1,p-1)
    A = pow(g,a,p)
    A = int(num_to_x_byte_str(A,384))
    
    cSocket.send(A.to_bytes(384,'big'))
    B = int.from_bytes(cSocket.recv(384),'big')
    password = pow(B,a,p)
    
    dh_string = create_final_dh_string(password)
    hash_dh_string = SHA256.new(dh_string)
    key = hash_dh_string.digest()[:32]
    

    data = sys.stdin.buffer.read()
    datalength = len(data)
    for i in range(0,datalength,1024):
        cipher = AES.new(key,AES.MODE_GCM)
        datablock = data[i:min(i+1024,datalength)]
        init_vector = cipher.nonce
        ciphertext, tag = cipher.encrypt_and_digest(pad(datablock,block_size=16,style='pkcs7'))
        blocklength = len(ciphertext) + 32
        datablock = blocklength.to_bytes(2,'big') + init_vector + tag + ciphertext
        cSocket.send(datablock)

    cSocket.shutdown(socket.SHUT_WR)
    cSocket.close()


def parse_args():
    """
    Command Line Argument Parser

    :return: Argparse Namespace of identified command line arguments.
    """
    # Configure the argument parser.
    parser = argparse.ArgumentParser(description='Encrypted File Transfer using Diffie-Hellman Key Exchange Protocol')
    server_group = parser.add_argument_group('server_group', 'Server mode options')
    server_group.add_argument('-l', dest='server_port', action='store', help='Server mode with port')
    client_group = parser.add_argument_group('client_group', 'Client mode options')
    client_group.add_argument('client_ip_address', nargs='?')
    client_group.add_argument('client_port', nargs='?')

    # Parse arguments.
    args = parser.parse_args()

    # Check if arguments are valid.
    args_ok = ((args.server_port is None) and (args.client_ip_address is not None and args.client_port is not None)) or \
              ((args.server_port is not None) and (args.client_ip_address is None and args.client_port is None))

    # If not, show usage message and exit.
    if not args_ok:
        print("./eft-dh [-l SERVER_PORT] [CLIENT_IP_ADDRESS CLIENT_PORT]")
        sys.exit(0)

    # Otherwise return the args.
    return args


def main():
    # Parse Arguments
    args = parse_args()

    # Launch the client or server depending on the arguments received.
    if args.server_port is not None:
        port = int(args.server_port)
        server(port)
    else:
        addr = args.client_ip_address
        port = int(args.client_port)
        client(addr, port)


if __name__ == "__main__":
    main()
